# Generated by Django 2.0.2 on 2020-03-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
